import asyncio
import json
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, WebSocket
from fastapi.responses import FileResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.config import settings
from app.database import get_db
from app.enums import JobStatus
from app.models import Job
from app.schemas import JobCreate, JobResponse
from app.services.email import send_report_email
from app.services.job import run_job

router = APIRouter(prefix="/api/jobs", tags=["jobs"])


@router.post("", status_code=201, response_model=JobResponse)
def create_job(data: JobCreate, db: Session = Depends(get_db)):
    job = Job(
        name=data.name,
        session_id=data.session_id,
        date=data.date,
        source_path=data.source_path,
        preset_id=data.preset_id,
        status=JobStatus.DRAFT,
    )
    db.add(job)
    db.commit()
    db.refresh(job)
    return job


@router.get("", response_model=list[JobResponse])
def list_jobs(db: Session = Depends(get_db)):
    return db.query(Job).order_by(Job.created_at.desc()).all()


@router.get("/{job_id}", response_model=JobResponse)
def get_job(job_id: int, db: Session = Depends(get_db)):
    job = db.get(Job, job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return job


@router.post("/{job_id}/run")
def start_job(job_id: int, db: Session = Depends(get_db)):
    job = db.get(Job, job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    if job.status not in (JobStatus.DRAFT, JobStatus.PARTIAL):
        raise HTTPException(status_code=400, detail=f"Job cannot be run from status {job.status}")

    try:
        result = run_job(db, job)
        return {
            "status": "complete",
            "verification": result.verification.value,
            "output_dir": result.output_dir,
            "report_path": result.report_path,
        }
    except (ValueError, Exception) as e:
        db.refresh(job)
        job.error_message = str(e)
        if job.status != JobStatus.ERROR:
            job.status = JobStatus.ERROR
        db.commit()
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/{job_id}/report")
def get_report(job_id: int, db: Session = Depends(get_db)):
    job = db.get(Job, job_id)
    if not job or not job.result:
        raise HTTPException(status_code=404, detail="Report not found")
    report_path = job.result.report_path
    if not report_path:
        raise HTTPException(status_code=404, detail="Report file not found")
    with open(report_path) as f:
        return json.load(f)


@router.get("/{job_id}/report/download")
def download_report_pdf(job_id: int, db: Session = Depends(get_db)):
    job = db.get(Job, job_id)
    if not job or not job.result:
        raise HTTPException(status_code=404, detail="Job not found")
    output_dir = job.result.output_dir
    if not output_dir:
        raise HTTPException(status_code=404, detail="No output directory")
    pdf_path = Path(output_dir) / "report.pdf"
    if not pdf_path.exists():
        raise HTTPException(status_code=404, detail="Report PDF not found")
    filename = f"{job.name}_{job.session_id}_report.pdf"
    return FileResponse(
        path=str(pdf_path),
        media_type="application/pdf",
        filename=filename,
    )


class SendCertificationRequest(BaseModel):
    recipients: str


@router.post("/{job_id}/report/send")
def send_certification(job_id: int, data: SendCertificationRequest, db: Session = Depends(get_db)):
    job = db.get(Job, job_id)
    if not job or not job.result:
        raise HTTPException(status_code=404, detail="Job not found")
    output_dir = job.result.output_dir
    if not output_dir:
        raise HTTPException(status_code=404, detail="No output directory")
    pdf_path = Path(output_dir) / "report.pdf"
    if not pdf_path.exists():
        raise HTTPException(status_code=404, detail="Report PDF not found")

    recipients = [r.strip() for r in data.recipients.split(",") if r.strip()]
    if not recipients:
        raise HTTPException(status_code=400, detail="No recipients specified")

    subject = f"[Braze Codes] Certification — {job.name} — {job.session_id}"
    body = (
        f'This certifies that barcoding job "{job.name}" '
        f"(Session: {job.session_id}, Date: {job.date.isoformat()}) "
        f"has been processed and verified.\n\n"
        f"Letters Processed: {job.result.total_documents}\n"
        f"Total Sheets: {job.result.total_sheets}\n"
        f"Barcodes Applied: {job.result.total_barcodes}\n\n"
        f"The attached report contains full processing details.\n\n"
        f"This certification was generated by Braze Codes."
    )

    pdf_bytes = pdf_path.read_bytes()
    pdf_filename = f"{job.name}_{job.session_id}_report.pdf"

    success = send_report_email(
        host=settings.smtp_host,
        port=settings.smtp_port,
        username=settings.smtp_username,
        password=settings.smtp_password,
        recipients=recipients,
        subject=subject,
        body=body,
        pdf_bytes=pdf_bytes,
        pdf_filename=pdf_filename,
    )

    return {"status": "sent" if success else "failed"}


@router.websocket("/{job_id}/ws")
async def job_progress(websocket: WebSocket, job_id: int):
    await websocket.accept()
    db = next(get_db())
    job = db.get(Job, job_id)
    if not job:
        await websocket.close(code=4004)
        return

    queue: asyncio.Queue = asyncio.Queue()
    loop = asyncio.get_event_loop()

    def progress_callback(current: int, total: int, msg: str = ""):
        loop.call_soon_threadsafe(queue.put_nowait, {
            "current": current,
            "total": total,
            "message": msg,
            "status": "processing",
        })

    try:
        task = asyncio.get_event_loop().run_in_executor(
            None, lambda: run_job(db, job, progress_callback=progress_callback)
        )

        while not task.done():
            try:
                msg = await asyncio.wait_for(queue.get(), timeout=0.5)
                await websocket.send_json(msg)
            except asyncio.TimeoutError:
                pass

        while not queue.empty():
            await websocket.send_json(await queue.get())

        result = await task
        await websocket.send_json({
            "current": result.total_documents,
            "total": result.total_documents,
            "message": "Complete",
            "status": "complete",
            "verification": result.verification.value,
        })
    except Exception as e:
        db.refresh(job)
        job.error_message = str(e)
        if job.status != JobStatus.ERROR:
            job.status = JobStatus.ERROR
        db.commit()
        await websocket.send_json({"status": "error", "message": str(e)})
    finally:
        await websocket.close()
        db.close()
